target 'PopToAppointedVCDemo' do

pod 'AFNetworking', '~> 3.0.4'
pod 'JSONModel', '~>1.1'
pod 'SWTableViewCell', '~>0.3.7'
pod 'MJRefresh', '~> 3.0.7'
pod 'SDWebImage', '~> 3.7.3'
pod 'Toast', '~> 3.0'

end